development:
  host: 127.0.0.1
  port: 27017
  username: anithaly
  password: super_secure_password_x54
  database: anithaly_questions

test:
  host: localhost
  database: questionnaire_app_test

# set these environment variables on your prod server
production:
  host: 127.0.0.1
  port: 27017
  username: anithaly
  password: super_secure_password_x54
  database: anithaly_questions
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
